#! /usr/bin/python
# -*- coding:utf-8 -*-
# notificador-mostrar V2.0
# Author: Matias Basso <mbasso@plan.ceibal.edu.uy>
#----------------------------------------------------------------------
# Muestra los mensajes vigentes dentro de la Base de Datos para Gnome.
#----------------------------------------------------------------------
from ceibal.notifier.viewer_gtk3 import *


# Start DBus Service
dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
session_bus = dbus.SessionBus()
name = dbus.service.BusName("edu.ceibal.NotificadorService", session_bus)
VentanaBoton(session_bus, "/Update")
